Application\Entity\UserEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: errors.user.email.alreadyInUse
            groups: [ new, edit, register, settings ]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: errors.user.username.alreadyInUse
            groups: [ new, edit, register, settings ]
    properties:
        username:
            - NotBlank:
                message: errors.user.username.notBlank
                groups: [ new, edit, settings ]
        email:
            - NotBlank:
                message: errors.user.email.notBlank
                groups: [ new, edit, settings, resetPasswordRequest ]
            - Email:
                message: errors.user.email.invalid
                groups: [ new, edit, settings, resetPasswordRequest ]
        plainPassword:
            - NotBlank:
                message: errors.user.password.notBlank
                groups: [ new, settingsPassword, resetPasswordReset ]
        profile:
            - Valid: ~
Application\Entity\ChatChannelEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name
            message: errors.chatChannel.name.alreadyInUse
            groups: [ newAndEdit ]
